#!/bin/bash

set -e

# Retrieve arguments
domain=$1
path=$2

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a dockerui \
	|| (echo "Path not available: $domain$path" && exit 1)

# Remove trailing "/" for next commands
path=${path%/}

# Check ports availability
sudo yunohost app checkport 9000
if [[ ! $? -eq 0 ]]; then
  exit 1
fi

# Install Docker if it is not installed yet
if [ -f /usr/bin/docker ]; then
	echo "Docker is already installed"
else
	echo "Docker will now be installed"
	sudo apt-get install curl -y -qq
	sudo curl -sSL https://get.docker.com/ | sh
	sudo yunohost service add docker
	sudo update-rc.d docker defaults
	sudo service docker start 
	sudo usermod -aG docker admin
	newgrp docker
fi
sudo service docker restart

# Create DockerUI container
sudo docker run -d --restart always -p 127.0.0.1:9000:9000 --privileged -v /var/run/docker.sock:/var/run/docker.sock --name dockerui dockerui/dockerui

# Configure Nginx and reload
sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/dockerui.conf
sudo service nginx reload
echo $?